/* (c) https://github.com/MontiCore/monticore */

plugins {
  id 'groovy'
  id 'java-gradle-plugin'
  id 'maven-publish'
}
description = 'se-commons: groovy'

dependencies {
    api project(":se-commons-utilities")
    api project(":se-commons-logging")
    implementation "org.jline:jline:$jline_version:jdk8"
    implementation "com.google.guava:guava:$guava_version"
    implementation "org.apache.groovy:groovy:$groovy_version"
    testImplementation "org.hamcrest:hamcrest:$hamcrest_version"
    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
    testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_version"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_platform_version"
}

gradlePlugin.plugins {
  segroovy {
    id = "se-groovy"
    implementationClass = 'de.monticore.SEGroovyPlugin'
  }
}