# (c) https://github.com/MontiCore/monticore

image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:7.5.1-jdk11

stages:
  - build
  - deploy
  - trigger_mc

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - "gradle build $GRADLE_OPT $ARGS1"
  artifacts:
    paths:
      - "target/"
      - ".gradle/"
    expire_in: 1 week

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - "gradle publish -PmavenPassword=$pass -PmavenUser=$user $GRADLE_OPT $ARGS2"
  only:
    - dev
  except:
    - master

trigger_mc_dev:
  stage: trigger_mc
  trigger:
    project: monticore/monticore
    branch: dev
  only:
    - dev

trigger_montiverse:
  stage: trigger_mc
  trigger:
    project: monticore/montiverseci
  variables:
    SECOMMONS_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    FULL_MC: "true" # also run MontiCore experiments
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
