/* (c) https://github.com/MontiCore/monticore */

plugins {
  id 'java-gradle-plugin' // No plugin will be published, but for tests
}

description = 'se-commons: gradle'

dependencies {
  implementation gradleApi()
  compileOnly project(":se-commons-logging") // CompileOnly to avoid dependency version pollution
  implementation "com.google.code.gson:gson:$gson_version"

  implementation "org.apache.commons:commons-lang3:$commons_lang3_version"
  implementation "com.google.guava:guava:$guava_version"
  implementation "com.github.spotbugs:spotbugs-annotations:$spotbugs_annotation_version"
}


// Test our plugin infrastructure with a test-plugin
sourceSets {
  testPlugin {
    compileClasspath += sourceSets.main.output
    runtimeClasspath += sourceSets.main.output
  }
}
configurations {
  testPluginImplementation.extendsFrom implementation
  testPluginRuntimeOnly.extendsFrom runtimeOnly
}

dependencies {
  testPluginImplementation gradleApi()
  testImplementation gradleTestKit()
  testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
  testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_version"
  testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit_version"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_version"
}
tasks.named('test', Test) {
  useJUnitPlatform()
  // Parallel test execution
  systemProperty("junit.jupiter.execution.parallel.enabled", true)
  systemProperty("junit.jupiter.execution.parallel.mode.default", "concurrent")
}

gradlePlugin {
  testSourceSet sourceSets.test
  plugins {
    cachedQueue {
      id = "se.rwth.gradle.cached-queue"
      implementationClass = "de.monticore.gradle.queue.CachedQueueServicePlugin"
    }
  }
}

tasks.register('testPluginJar', Jar) {
  archiveClassifier = 'testPlugin'
  from sourceSets.testPlugin.output
}

tasks.pluginUnderTestMetadata {
  pluginClasspath.from(tasks.testPluginJar)
}
